[install]
state = enabled
is_configured = false
build = 1

[launcher]
author = Robert Phillips
description = Run splunk btool check from the search bar to find typos and invalid keys in .conf files.
version = 1.0.0

[ui]
is_visible = true
label = Btool Check for Splunk

[package]
id = TA-btool-check
check_for_updates = true
